# --- Serving options --- #

url: "http://blog.givingjar.org"
baseurl: ""

# Name of website
title: Giving Jar Blog

# Short description of your site
description: Discover Giving Jar, Nonprofits, and Charitable Giving

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/giving-jar-icon-square.svg"

# List of links in the navigation bar
navbar-links:
  Newsletter: "http://givingjar.org"
  Spotlights: "/tag/spotlight/"
  About: "/about/"

# --- Tag Information --- #

tag_permalink_style: pretty
tag_page_layout: tag
tag_page_dir: tag

tag_meta:
  progress-report:
    title: Progress Reports
    subtitle: Little updates every other week so you know how Giving Jar is coming along.
  spotlight:
    title: Charity Spotlights
    subtitle: Interviews with unsung charities that are doing amazing good in the world. Updated every other week.

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: "Giving Jar, LLC"
  url: http://givingjar.org
  email: "hello@givingjar.org"
  facebook: givingjarorg
  twitter: givingjar

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: true
  email: true
  twitter: true
  github: false
  linkedin: false
  stackoverflow: false

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-62666024-5"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
future: false
timezone: "UTC"
markdown: kramdown
highlighter: pygments
permalink: /:year-:month-:day-:title
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - Gruntfile.js
  - node_modules
