[build]
  publish = "_site"
  command = "jekyll build"

[context.master]
  command = "jekyll build --config _config.yml,_config.test.yml"

[context.netlify]
  command = "jekyll build --config _config.yml,_config.test.yml"
